#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    
    #splitting the strings and storing in a list
    words = s.split(' ')
    for i in range(len(words)):
        
        #capitalizing the first index of every elemnt in the list 
        words[i]=(words[i].capitalize())
    
    #joining the elements with a space
    return(' '.join(words))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    s = input()
    result = solve(s)
    fptr.write(result + '\n')
    fptr.close()
